import profile from "../../images/profile-pic.jpeg";
import askQns from "../../images/askingquestion.avif";
import img1 from "../../images/img1.jpeg";
import img2 from "../../images/img2.png";
import img3 from "../../images/img3.jpeg";


const Postsarray = [
  {
    img: profile,
    name: "Naveen",
    qns: "What is the scope of AI?",
    qnsImg: img3,
    category: "AI",
    date: "2023-06-25T12:00:00Z",
    likes: 12,
  },
  {
    img: profile,
    name: "Abdul",
    qns: "What is Data Structure?",
    qnsImg: img1,
    category: "DSA",
    date: "2023-06-24T12:00:00Z",
    likes: 5,
  },
  {
    img: profile,
    name: "Naseer",
    qns: "Should I learn DSA or React?",
    qnsImg: img2,
    category: "DSA",
    date: "2023-06-23T12:00:00Z",
    likes: 20,
  },
  {
    img: profile,
    name: "Hari Babu",
    qns: "Is there a future for Cloud?",
    qnsImg: askQns,
    category: "Cloud",
    date: "2023-06-22T12:00:00Z",
    likes: 15,
  },
  {
    img: profile,
    name: "Sri Ram",
    qns: "What is the highest package at the college?",
    qnsImg: img1,
    category: "College",
    date: "2023-06-21T12:00:00Z",
    likes: 7,
  },
  {
    img: profile,
    name: "Maha Sai",
    qns: "What is the best course for Spring Boot?",
    qnsImg: img2,
    category: "Web Development",
    date: "2023-06-20T12:00:00Z",
    likes: 9,
  },
  {
    img: profile,
    name: "Asha",
    qns: "How to start with Machine Learning?",
    qnsImg: img3,
    category: "ML",
    date: "2023-06-19T12:00:00Z",
    likes: 14,
  },
  {
    img: profile,
    name: "Ravi",
    qns: "What are the best practices in Cybersecurity?",
    qnsImg: img3,
    category: "Cybersecurity",
    date: "2023-06-18T12:00:00Z",
    likes: 11,
  },
  {
    img: profile,
    name: "Lakshmi",
    qns: "Can anyone suggest resources for Big Data?",
    qnsImg: img2,
    category: "Big Data",
    date: "2023-06-17T12:00:00Z",
    likes: 13,
  },
  {
    img: profile,
    name: "Raj",
    qns: "What are the key concepts in DevOps?",
    qnsImg: img2,
    category: "DevOps",
    date: "2023-06-16T12:00:00Z",
    likes: 8,
  },
  {
    img: profile,
    name: "Geeta",
    qns: "How to optimize database performance?",
    qnsImg: img1,
    category: "DBMS",
    date: "2023-06-15T12:00:00Z",
    likes: 10,
  },
  {
    img: profile,
    name: "Suresh",
    qns: "What is the future of Networking?",
    qnsImg: img3,
    category: "Networking",
    date: "2023-06-14T12:00:00Z",
    likes: 6,
  },
  {
    img: profile,
    name: "Priya",
    qns: "How to get started with Data Science?",
    qnsImg: img1,
    category: "Data Science",
    date: "2023-06-13T12:00:00Z",
    likes: 18,
  },
  {
    img: profile,
    name: "Vishnu",
    qns: "What are the latest trends in AI?",
    qnsImg: img3,
    category: "AI",
    date: "2023-06-12T12:00:00Z",
    likes: 17,
  },
  {
    img: profile,
    name: "Kiran",
    qns: "How to learn DSA efficiently?",
    qnsImg: img1,
    category: "DSA",
    date: "2023-06-11T12:00:00Z",
    likes: 22,
  },
  {
    img: profile,
    name: "Anil",
    qns: "What are the benefits of Cloud Computing?",
    qnsImg: img2,
    category: "Cloud",
    date: "2023-06-10T12:00:00Z",
    likes: 16,
  },
  {
    img: profile,
    name: "Manisha",
    qns: "Best practices in Web Development?",
    qnsImg: askQns,
    category: "Web Development",
    date: "2023-06-09T12:00:00Z",
    likes: 19,
  },
  {
    img: profile,
    name: "Nikhil",
    qns: "How to secure web applications?",
    qnsImg: img3,
    category: "Cybersecurity",
    date: "2023-06-08T12:00:00Z",
    likes: 21,
  },
  {
    img: profile,
    name: "Meena",
    qns: "What are the best resources for Big Data?",
    qnsImg: img3,
    category: "Big Data",
    date: "2023-06-07T12:00:00Z",
    likes: 23,
  },
  {
    img: profile,
    name: "Sunil",
    qns: "Key tools for DevOps?",
    qnsImg: img1,
    category: "DevOps",
    date: "2023-06-06T12:00:00Z",
    likes: 24,
  },
];

export default Postsarray;
